### ISSUE TITLE
item 975 misprinted as 978 in Memofonte edition

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-catalogo#10]
(from a comparison of the digital page-image facsimile of the Getty copy of the 1821 edition stored in HathiTrust).

I suggest editing the TEI edition to match the original 1821 edition and noting the discrepancy somewhere.

**Comment by cwulfman** [comment]
I generated the sequence of catalogo item labels (cico numbers) from both _Catalogo_ volumes and searched for discontinuities. Some were due to automated tagging errors (I repaired these silently); others were from misprints in the Memofonte edition. I corrected the TEI file to match the 1821 edition of the _Catalogo_ and noted the changes in the encodingDesc.

**Comment by jpstroop** [comment]
Should we have a separate Github label specifically for for numbering errors, in case we ever want to report them out? Or is it enough to have this info in the TEI?
