### ISSUE TITLE
Bib 8543477 -- Bring Two Volumes Under One Master/ Root Record?

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#101]
Hi folks,

Should these two volumes be under one record?

https://figgy.princeton.edu/catalog/4cbc05e0-83d9-424b-957c-5d3ce4c970ee
https://figgy.princeton.edu/catalog/19edf670-23a5-43e7-8b26-def34e486a71

Make sense?

Thanks!

**Comment by lightgivener** [comment]
Yes!

 

They are confusingly similar but the Vatican has them as Volumes and the publication dates are 1731 (vol.1) and 1732 (vol.2). Matching copies Getty etc listed as volumes and same dcl identifier also add up.

 



	
		
		
	
	
		
			DCL Nr
			volumes (old info)
			Matching (Lname + pub date)
		
		
			x2g
			x2g/vol01
			Gori1731
		
		
			x2g
			x2g/vol02
			Gori1732
		
	



 

Thanks!

 
 

Gesendet: Mittwoch, 12. Februar 2020 um 21:44 Uhr
Von: "David Platt" <notifications@github.com>
An: pulibrary/cicognara-catalogo <cicognara-catalogo@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [pulibrary/cicognara-catalogo] Bib 8543477 -- Bring Two Volumes Under One Master/ Root Record? (#101)


Hi folks,

Should these two volumes be under one record?

https://figgy.princeton.edu/catalog/4cbc05e0-83d9-424b-957c-5d3ce4c970ee
https://figgy.princeton.edu/catalog/19edf670-23a5-43e7-8b26-def34e486a71

Make sense?

Thanks!
