### ISSUE TITLE
Bib 8543474 -- Nest Structmapped Duplicates Under Main Record?

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#104]
Hi folks,

One of our super-enthusiastic student workers has accidentally structmapped two "floating" duplicates. So that their hard work isn't wasted, could you please attach:

https://figgy.princeton.edu/catalog/13815e10-eca8-4851-9231-ad5de4b693a3
AND
https://figgy.princeton.edu/catalog/97189f79-ea7a-4cb5-abb0-4306ab1a9beb

UNDER: https://figgy.princeton.edu/catalog/adeb9637-b29d-4663-9b6e-3eea3705ce5f 

??

And if you could also save me some time and zap the two unmapped volumes, I'd be SUPER grateful.

Thanks and best wishes,

-- David

**Comment by lightgivener** [comment]
@smallfind @tpendragon  I am sorry, could someone give me a hint how I can change the item title that also appears in the structmap? For these multi-volume items it would be mighty practical if you don't just have the same title repeat in the structmap overview but could add something like vol. 1 and vol.2 or the publications date difference in this case.

thanks!

PS: Hope you are all holding up well!
