### ISSUE TITLE
Bib 8534271 -- Please Merge 1 Structmapped Partial Set with 1 Unstructmapped Complete Set

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#109]
Hi folks,

Please bring the 2 volumes in this set (https://figgy.princeton.edu/catalog/659441cc-ee7b-4e6d-a3ed-5c868d8a9813) under the wing of this record (https://figgy.princeton.edu/catalog/a8434cb4-7db2-448d-a73c-30d2c580de44).

Bonus Brownie Points if you can zap the duplicate unmapped volumes AND mark the whole thing as "final review."

Thanks and best wishes,

-- David

**Comment by tpendragon** [comment]
@smallfind Neither of the volumes in that first set appear to be struct-mapped. Are you sure?

**Comment by smallfind** [comment]
I have no idea what happened there. 🙄 😳 Thanks for your patience. I've just zapped the duplicate.
