### ISSUE TITLE
Catalogo item with no number

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-catalogo#11]
See, in 1821 edition (p. 115) an item between 637 and 638:
![missingnum](https://cloud.githubusercontent.com/assets/891097/14720531/e9fcfb18-07cf-11e6-97ac-d5573af8f0ad.jpg)
Memofonte cheats by assigning it the next number in sequence and then doubling up later:
![memofonte](https://cloud.githubusercontent.com/assets/891097/14720750/f3b33108-07d0-11e6-9eac-ff8f0e836689.jpg)

I can't find the Le Roux in the marc data; perhaps someone else can?

**Comment by joycebcat** [comment]
I can't find a MARC record for the title.  Possibly a bound-with or something of that nature.  We will revisit when we have the images for 637 and/or images for the missing title.
