### ISSUE TITLE
Bib: 8544329 -- Catalogo Nr. 3929 (1) and (2) Are Attached to Wrong Figgy Record

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#113]
Hi folks:

- The images at https://figgy.princeton.edu/catalog/2644c3cd-7636-4f8c-a7a2-a0a0197f68be should be attached to Bib 8544329 -- instead they are attached to Bib 8545262 
- [By comparison, there's a correct version of Bib 8545262 here: https://figgy.princeton.edu/catalog/6d4bf527-b35f-483d-936e-24c529b4a681 ]

Does this make sense?

Thanks and best wishes,

-- David

**Comment by smallfind** [comment]
(Sorry. Should I be attaching folks to these jobs? 😳 )

**Comment by tpendragon** [comment]
@smallfind I just moved it over. You should be able to do this in the future by editing the record and changing the "Source Metadata Identifier"
