### ISSUE TITLE
Two items numbered 3922 and no 3923 in the 1821 edition

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-catalogo#12]
The Memofonte edition leaves the second item unnumbered.
Almost certainly the second 3922 should be labeled 3923. Someone needs to confirm this. Meanwhile, I will tag it so in the TEI transcription.

**Comment by joycebcat** [comment]
@cwulfman Yes, this seems to be the case.  The 3923 number has been associated with the second unnumbered item in our MARC data for the microfiche, and therefore repeated in our 024 field.

**Comment by cwulfman** [comment]
Great; I'll close this ticket, then.
