### ISSUE TITLE
Bib: 8543039 -- Bring All These Structmapped Volumes Under One MVW?

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#120]
Hi folks,

Here's another. Can you bring these structmapped items:

https://figgy.princeton.edu/catalog/dccad3b5-1c54-4660-8f70-90bcefcf757b
https://figgy.princeton.edu/catalog/bde2b0b5-27b6-488a-94ec-c36df1924d41
https://figgy.princeton.edu/catalog/492a4a32-d112-41ff-b584-deb327d916d6

AND https://figgy.princeton.edu/catalog/aee21a8d-468c-453a-8b05-17f49a34d051

**Under this one?** https://figgy.princeton.edu/catalog/a1be28d8-5426-497c-bdd0-e70d7ebe1b4d

Thanks!

- d

**Comment by tpendragon** [comment]
These have been moved. Can you close this after you check it @smallfind ?

**Comment by smallfind** [comment]
Looks like only one of them made it (https://figgy.princeton.edu/catalog/bde2b0b5-27b6-488a-94ec-c36df1924d41). Alas! 

Could you try again with:
https://figgy.princeton.edu/catalog/aee21a8d-468c-453a-8b05-17f49a34d051
https://figgy.princeton.edu/catalog/492a4a32-d112-41ff-b584-deb327d916d6
https://figgy.princeton.edu/catalog/dccad3b5-1c54-4660-8f70-90bcefcf757b

(Sorry!)

**Comment by tpendragon** [comment]
@smallfind If you go to https://figgy.princeton.edu/catalog/a1be28d8-5426-497c-bdd0-e70d7ebe1b4d and scroll to the bottom there's a field "attach an existing resource by ID." If you put in the resource IDs for the individual volumes there one at a time and attach them you should be able to do this without waiting for me. So, for instance, you'd put aee21a8d-468c-453a-8b05-17f49a34d051 in there to attach https://figgy.princeton.edu/catalog/aee21a8d-468c-453a-8b05-17f49a34d051.

Would you mind trying so we can make sure it's working for you?

**Comment by smallfind** [comment]
I'm afraid I get an error message: 

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

**Comment by smallfind** [comment]
Hang on.
