### ISSUE TITLE
several Figgy entries for one set

### ISSUE THREAD

**Issue by lightgivener** [pulibrary/cicognara-catalogo#123]
Hey!

Set of 2 volumes bound in 3 has one Figgy record with all volumes in one viewer [https://figgy.princeton.edu/catalog/2097f0a4-85d8-45db-a420-259b01c1d674] , but then also some superflous additional single volume viewers. All local Identifier dcl:f8c.

can likely be deleted:
https://figgy.princeton.edu/catalog/f87cfb2f-4b08-4de2-8dc7-a89a6e1496e4
https://figgy.princeton.edu/catalog/09dfd6d9-1c97-46ad-9a4e-a211121bacb7

**Comment by smallfind** [comment]
OK. Got 'em. Thanks!
