### ISSUE TITLE
dcl:rvb, Bib: 8524824, Bib: 8494356 -- A Mix Up

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#125]
Hi folks,

A couple of problems: 
- It looks like one set of images (here: https://figgy.princeton.edu/catalog/83fd93b2-1cf6-4458-9fc4-e566f2260cb4) should be attached to a different Bib (https://catalog.princeton.edu/catalog/8494356).
  - Can you please attach it to the correct record?
- In addition: While this one (https://figgy.princeton.edu/catalog/5f0a83b2-52e2-408d-a525-b870663e99fb) is actually attached to the right bib (https://catalog.princeton.edu/catalog/8524824), **somehow** images from the 8494356 microfiche headers have been put at the front. 
  - A candidate for a re-shoot?

Thanks!

**Comment by smallfind** [comment]
See also: https://github.com/pulibrary/cicognara-catalogo/issues/103

**Comment by tpendragon** [comment]
@smallfind I fixed https://figgy.princeton.edu/catalog/83fd93b2-1cf6-4458-9fc4-e566f2260cb4. Can you make another ticket for the second issue and close this one?

**Comment by smallfind** [comment]
On it!
