### ISSUE TITLE
Bib 8543086 -- Bring 18 (EIGHTEEN!!!) Individual Volumes Under One MVW?

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#128]
If you would be so kind, please. 😀

(No need for you to order and zap any duplicates--I can handle both those tasks.)

**Comment by tpendragon** [comment]
@smallfind Done: https://figgy.princeton.edu/catalog/16b13aee-6be3-4c71-9b5e-ede82ea48d53

**Comment by smallfind** [comment]
Thanks!

(And I feel silly for asking this but can you tell me why there's a "claim" button at the top of this record?)

**Comment by tpendragon** [comment]
@smallfind "Claim" is just a new Figgy feature to allow users of Figgy to take an item as "theirs" to work on. It populates a facet in the search results so they can "View Items Claimed by Me"
