### ISSUE TITLE
973 marc records with 'malformed' cico numbers

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-catalogo#13]
Attached to this ticket is an xml file representing the marc records that still have 'non-standard' cico numbers: \d+[\w]+, \d+BIS, \d+-\d+, etc. I.e., these records have no equivalent in the catalogo transcription.

The dclib numbers in these records are unique: that is, they are not associated with any "good" records (those that do have equivalents in the catalogo)

These are the mappings that need to be normalized before splicing the dclib numbers into the transcription.
[badrecords.xml.zip](https://github.com/pulibrary/cicognara-catalogo/files/230878/badrecords.xml.zip)

**Comment by jpstroop** [comment]
Any reason not to put that file in the Git repo?

**Comment by cwulfman** [comment]
I'd been thinking of that file as ephemeral; didn't want to spam the repo. Would you like me to include it?

**Comment by jpstroop** [comment]
I guess I don't know how you intend to use it, but if it's a list of problems and you're going to be knocking them off over time, seems like versioning might help. But whatev.

**Comment by joycebcat** [comment]
These are numbers which have been associated with the object in their "malformed" state.  As such, we will retain them in the 024 fields as legitimate identifiers used for the object in one of its manifestations.

This ticket can be closed.

**Comment by cwulfman** [comment]
Ok. See subsequent tickets; I went ahead and normalized these numbers and spliced them into the TEI.
