### ISSUE TITLE
Bib 8524701 -- Please Delete Duplicate Images

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#130]
Sorry, folks -- I don't think I have this superpower.

Please delete image 73-img 108 inclusive (they duplicate image 37-72): https://figgy.princeton.edu/catalog/ff49c979-fd30-45b2-8802-c979cc5e5be2

Thanks and best wishes,

-- David

**Comment by tpendragon** [comment]
@smallfind Can you use the order manager and name the pages you want gone something like "DELETE ME"?

**Comment by smallfind** [comment]
OK. How's that?

**Comment by tpendragon** [comment]
@smallfind Deleted. Can you close this ticket if it looks good?

**Comment by smallfind** [comment]
Will do as soon, when I post this comment! Thanks for all your help!
