### ISSUE TITLE
wrong dcl identifier in PU file directory

### ISSUE THREAD

**Issue by lightgivener** [pulibrary/cicognara-catalogo#131]
@smallfind 

Hey David,

Found a wrong dcl identifier on a fiche scan. Guess it's a typo.

The fiche is Cico No 237 _Trattato della Pittura 1817_ which should be dcl:vv9 taken from the ShotList, but in the files directory and subsequently Figgy it is dcl:0w9 which links to another title (Cico No 3239 _De diptycho Brixiano Boethii_).

Please fix the Trattato della Pittura fiche scan file to dcl_vv9

Thanks!

**Comment by smallfind** [comment]
Hey Charlotte,

So, this is the file that needs to be fixed: https://figgy.princeton.edu/catalog/60e7ee99-04a3-48bc-9d5b-5b973dc75ff9 // It should be attached to this Bib Record: https://catalog.princeton.edu/catalog/8529498

This is the file that's okay: https://figgy.princeton.edu/catalog/ef5db0de-7e0b-48a9-87da-a47fac4e4d89

@tpendragon  , this may be beyond my ken. Would you have a go at re-linking the first to the correct record please? 

Thanks! 😀

**Comment by tpendragon** [comment]
@smallfind I think it's fixed. Can you close if so?

**Comment by smallfind** [comment]
Looks good! Thanks so much! (And, now that I do how to do this myself, I shouldn't have to pester you with one like this again. Thanks for your patience!)

**Comment by lightgivener** [comment]
Hey there! The fix looks good but I overlooked that it is a Double Number instead of volumes - my mistake, sorry!

Not a big fix, it just means that fiche header '237' (2 volumes bound as one) needs to be seperated into one viewer, and the two other fiche need to stay together displayed in a seperate viewer.


So fiche header '237' dcl:vv9  Trattato and Disegno bound together in one viewer.

And fiche header '237BIS(1)' Trattato dcl:1ps/vol01
+ '237BIS(2)' Disegno dcl:1ps/vol02 together in another viewer.

Thanks!


Cico-Nr. | Double   Number | Author | Title | Place | Year | Cico-Nr. / Original  (as on fiche   header) | Total   Number of Works | DCL Nr
-- | -- | -- | -- | -- | -- | -- | -- | --
237 | (1st copy) | Leonardo da   Vinci*1452-1519*; Guglielmo Manzi | Trattato della pittura di Lionardo da Vinci : … Disegni che illustrano l'opera | Roma : De   Romanis | 1817 | 237 | 0 | vv9
237bis-1 | (2nd copy in two parts) | Leonardo da   Vinci*1452-1519* | Trattato della pittura di Lionardo da Vinci : | Roma : De   Romanis | 1817 | 237bis<1> | 1 | 1ps
237bis-2 | (2nd copy in two parts) | Leonardo da   Vinci*1452-1519*; Guglielmo Manzi | [Trattato della pittura] Disegni che illustrano l'opera del Trattato | Roma | 1817 | 237bis<2> | 1 | 1ps
