### ISSUE TITLE
spurious quotation marks around ciconum in marc record for voyagerid 7928617

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-catalogo#14]
Truncated for brevity:

`   <record>
        <leader>03064cam a2200481Ia 4500</leader>
        <controlfield tag="001">7928617</controlfield>
        <controlfield tag="005">20160420000216.0</controlfield>
        <controlfield tag="006">m     o  d        </controlfield>
        <controlfield tag="007">cr mn |||||a|a</controlfield>
        <controlfield tag="008">120912s1521    it      s     000 0 lat d</controlfield>
        <datafield ind1=" " ind2=" " tag="035">
            <subfield code="a">(OCoLC)ocn809796708</subfield>
        </datafield>
        <datafield ind1="7" ind2=" " tag="024">
            <subfield code="a">"3789"</subfield>
            <subfield code="2">cico</subfield>
        </datafield>
        <datafield ind1="7" ind2=" " tag="024">
            <subfield code="a">cico:hrq</subfield>
            <subfield code="2">dclib</subfield>
        </datafield>`

**Comment by joycebcat** [comment]
Marc record updated.

This issue can be closed.

**Comment by cwulfman** [comment]
Thanks!
