### ISSUE TITLE
Bib 8541788 -- Please Bring 'Mapped Volumes Under One MVW?

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#140]
Hi folks,

Please drag

https://figgy.princeton.edu/catalog/08147dd5-04f6-4612-8105-0543a9b993cf

and

https://figgy.princeton.edu/catalog/897c479a-6b45-415d-a92f-5335dd050f57

into this MVW

https://figgy.princeton.edu/catalog/2a240dab-5e82-42b9-82c1-9fff091527e3

Once this is done, I'll complete the deletions of unmapped volumes.

Thanks! :^)

-- David

**Comment by tpendragon** [comment]
Done (through UI - just scroll to the bottom of the MVW and put the resource ID from the URL in the "Attach an existing resource by ID..." box)
