### ISSUE TITLE
newly inserted items appear twice

### ISSUE THREAD

**Issue by lightgivener** [pulibrary/cicognara-catalogo#142]
Hey,

I just checked for nearly added Frick matches and it seems the newly inserted items again apear twice each? Since it is so great the doubling from before was fixed I wanted to let you know just in case this now repreats the old problem.

https://cicognara.org/catalog/40

Thanks!

**Comment by tpendragon** [comment]
This is because there's two in Getty with the same manifest:
http://portal.getty.edu/books/frick_932304351 and http://portal.getty.edu/books/frick_b13793548

**Comment by tpendragon** [comment]
This'll fix itself when there aren't two in Getty. Closing.
