### ISSUE TITLE
Bib 8530226 / dcl:tjn -- Additional (Erroneous) Title Showing in Figgy Metadata -- But Not Source Metadata

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#144]
Hi folks,

For some reason:

https://figgy.princeton.edu/catalog/d53225bf-c9df-49c8-9056-8c6e8f2d3b33

lists two titles:

anach des beaux-arts
Almanach des beaux-arts

The first seems to be erroneously included (and a truncated version of "Almanach"?). But I don't see it in the PUL Voyager/ OPAC records either: https://catalog.princeton.edu/catalog/8530226

I've tried removing the error in the "Edit scanned resource" tool. It does not stick, for whatever reason.

Any idea what's going on here?

Thanks,

-- David

**Comment by tpendragon** [comment]
Yeah, it's a recent bug - sort titles are showing in the title. We have it in as a ticket, but some other functionality we're working on has taken priority.

**Comment by smallfind** [comment]
Understood. (I'll leave the issue open, for now -- unless you object.)

Thanks!

**Comment by tpendragon** [comment]
I refreshed the title for that item. Closing.
