### ISSUE TITLE
National Gallery Library London would like name changed on Cico.org

### ISSUE THREAD

**Issue by lightgivener** [pulibrary/cicognara-catalogo#149]
Hey!

Jonathan from the NG London send us this message through the Cico.org messaging function, could you be so kind and change? Cheers, Charlotte

"name:Jonathan Franklin

comment:On the Partners page https://cicognara.org/partners please can the National Gallery Library be listed as 'National Gallery, London'. It would be preferable to remove the words 'National Art Library' so as not cause confusion with the National Art Library at the Victoria and Albert Museum. Many thanks Jonathan"

**Comment by escowles** [comment]
Issue moved to [pulibrary/cicognara-rails #481](https://github.com/pulibrary/cicognara-rails/issues/481) via [**ZenHub**](https://www.zenhub.com/)
