### ISSUE TITLE
Metadata for Volumes Within Multi-Volume Works?

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#152]
It's been noted that the automatically ingested volumes of MVWs all have the same title in the viewer's index and that this can be a little overwhelming and disorienting.

May I ask the group if the following works?

For each  single volume within the set, delete the "Source Metadata ID" (e.g., 8516765), save the record, and add the preferred title in the title field (e.g. "Vol. 1", "Tome I", etc.). Then put the DCL # (e.g., dcl:50g) and the PUL Bib # (e.g., 8516765). Save again.

I have a worked example here: https://figgy.princeton.edu/catalog/66f0fc80-9e17-4762-a184-1e180879d7ca

Does this look okay?

**Comment by escowles** [comment]
@smallfind Yes, I think that looks great. I think when we bulk-ingested many of these items, we put the Bib ID in the parent and each child, and that's really not the best way to do it. So I think updating them as you describe makes them much more readable.

**Comment by smallfind** [comment]
My big concern was if the child got detached without any obvious link to the parent in its own record. I'm a little worried that I'll need to go back and check old work, as I tried to hash this one out.

**Comment by smallfind** [comment]
(Oh, and THANKS!)
