### ISSUE TITLE
[Potentially Confusing] dcl:6pb; s52; and s52-2

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#155]
Folks,

I've just had to do some juggling of images and records in Figgy.

- 6pb = Bib 8493988 and was A-OK. (https://figgy.princeton.edu/catalog/db9330fa-9046-4c37-9662-b683db919845)
- s52 (Crowley Box 48) ALSO = Bib 8493988 but was linked to Bib 8493959. I re-linked it to Bib 8493988. (https://figgy.princeton.edu/catalog/a7c77179-b52e-4d78-ae60-fe4ada20800c)
- images in Box 48 for s52-2 images were not uploaded to Figgy and should have been linked to Bib 8493959 (https://figgy.princeton.edu/catalog/9dac5565-e0b8-483d-be01-cc00d21cd7fa)

So I think I have fixed almost everything. **However**:

- I have no idea how to handle the dcl:s52 and dcl:s52-2 identifiers.
- I don't control the master list of dcl identifiers and am no longer sure how does.

Please advise.

**Comment by escowles** [comment]
@smallfind I can get new DCL numbers. Just to be clear, it looks like the first two items are good (the second one has a manually-entered DCL number = dcl:s52, so I just need to get a new DCL number and add it to the third item (https://figgy.princeton.edu/catalog/9dac5565-e0b8-483d-be01-cc00d21cd7fa). Is that right?

**Comment by smallfind** [comment]
That sounds right, yeah!

**Comment by escowles** [comment]
@smallfind OK, I've taken `dcl:bd2` from the list of available DCL numbers, so you can add it to https://figgy.princeton.edu/catalog/9dac5565-e0b8-483d-be01-cc00d21cd7fa when you're ready

**Comment by smallfind** [comment]
Great! (I'll have to put a note in to change it in Alma, as Voyager is closed and I'm not sure if I can change this in Alma yet.)

Thanks.

**Comment by escowles** [comment]
@smallfind 👍🏻 I went ahead and put `dcl:bd2` in the local identifier field — though I notice that it's still using `dcl:s52` in the manifest (taken from the MARC record). So fixing this in Alma so that is updated sounds good.

**Comment by smallfind** [comment]
Got it. I made the edits in the Marquand cataloging location. I am hoping that this appears in the OPAC overnight.
