### ISSUE TITLE
New dcl for Bib 8534048/ dcl:knx? [EDIT: And dcl:xbr/ Bib 8533971, Please.]

### ISSUE THREAD

**Issue by smallfind** [pulibrary/cicognara-catalogo#157]
Hi folks,

There are two duplicate physical copies of Bib 8534048 in the original library.
- For some reason, these were originally photographed/ microfiched with the same fiche nr. ("Cicognara collection contains two copies; there are two fiche numbered 1993 reflecting this." -- https://catalog.princeton.edu/catalog/8534048).
- The external vendor imaged them as vol01 and vol02 (see Batch 03, Box 18) and they were uploaded as two volumes of a MVW.
- I deleted these and re-uploaded them as two separate copies (https://figgy.princeton.edu/catalog/b6b4d5c1-0a50-426f-bce9-feb0e55692fd AND https://figgy.princeton.edu/catalog/db45116f-aede-46be-81b8-13fc8b06aa3e).
- However, I think that one of these should have a separate dcl. Would you pull a number for me please?

Thanks!

**Comment by smallfind** [comment]
And the same has happened with dcl:xbr/ Bib 8533971 (also Box 18):

- Copy 01: https://figgy.princeton.edu/catalog/2f4e6669-e2be-4621-a06d-4e027a8584dd
- Copy 02: https://figgy.princeton.edu/catalog/13695208-e739-4477-88db-607f8372d00c

**Comment by escowles** [comment]
@smallfind OK, I've grabbed new DCL numbers for those:
* dcl:wjz for the second copy of 1993
* dcl:995 for the second copy of 1996

**Comment by smallfind** [comment]
Thanks!
