### ISSUE TITLE
non-numeric values for ciconums

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-catalogo#16]
"n.C.n." presumably means "not a Cicognara number"? Don't know what MFC signifies.

1. 8494058 (MFC  128)
2. 8546077 (n.C.n.)
3. 8546364 (n.C.n.  IV M 61 (3))

**Comment by joycebcat** [comment]
@cwulfman I just removed these 024s from the MARC records since they aren't cico numbers.  The dclib numbers are unaffected.

This issue can be closed.

**Comment by cwulfman** [comment]
Ok; thanks @joycebcat
