### ISSUE TITLE
Problem with schema

### ISSUE THREAD

**Issue by lmas2019** [pulibrary/cicognara-catalogo#2]
In line 1 of "Catalogo_Cicognara-1",there is a red box. OxyGen says it can't validate without schema. I can't see where the problem is in line 1.
GitHub seems to say I made changes to the actual schema, but I don't see how I changed it.
Do I sync the changes so you could see how the schema has been changed?

**Comment by cwulfman** [comment]
Interesting — it’s looking for the schema file, and line 1 should be telling it where to find it, relative to where the file is. Have you moved the file anywhere?

—C

On Feb 21, 2016, at 8:32 PM, lmas2019 <notifications@github.com<mailto:notifications@github.com>> wrote:


In line 1 of "Catalogo_Cicognara-1",there is a red box. OxyGen says it can't validate without schema. I can't see where the problem is in line 1.
GitHub seems to say I made changes to the actual schema, but I don't see how I changed it.
Do I sync the changes so you could see how the schema has been changed?

**Comment by lmas2019** [comment]
I did change the location, but I'm not sure how put the new location information into that line. I guess it goes in the 'encoding' tag? I'm not sure how to identify its new location in the tag.

**Comment by cwulfman** [comment]
Why did you move the file? It really needs to stay where it is, so the schema links up properly, for one thing, and so git can manage it properly.

—C


On Feb 21, 2016, at 9:01 PM, lmas2019 <notifications@github.com<mailto:notifications@github.com>> wrote:


I did change the location, but I'm not sure how put the new location information into that line. I guess it goes in the 'encoding' tag? I'm not sure how to identify its new location in the tag.

**Comment by lmas2019** [comment]
I moved the file to put all the Cicognara files in one folder. I didn't think there would be a problem with the file location, as it could always be reassigned. Should I try to move the schema back?

**Comment by cwulfman** [comment]
Yes; keep them all where they were when you cloned them in git. If you think we need to move them around, let me know and we can talk about it.

**Comment by lmas2019** [comment]
I moved them back into the original Cicognara file under the user home heading, but it didn't help with the  issue on line 1

**Comment by cwulfman** [comment]
The files should be arranged something like this:


![cico window](https://cloud.githubusercontent.com/assets/891097/13207851/594bb400-d8e1-11e5-875c-375a491156fa.jpg)

**Comment by lmas2019** [comment]
I arranged them that way but the issue isn't fixed
![image](https://cloud.githubusercontent.com/assets/17343693/13208033/ed9a032c-d8e2-11e5-93c7-570240b267ca.png)

**Comment by lmas2019** [comment]
![screen shot 2016-02-21 at 9 33 17 pm](https://cloud.githubusercontent.com/assets/17343693/13208037/f908847c-d8e2-11e5-9d9a-c4816a7c3b06.png)

**Comment by lmas2019** [comment]
Resolved - Opened file in correct location.
