### ISSUE TITLE
missing text chunk

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-catalogo#24]
Cliff,
My student was adding the pb tags this afternoon when she noticed something strange—a big chunk of text missing in the TEI.  If you look at around line 5921 you’ll see where page 68 should go in, but the text from the PDF is not reflected in the TEI.  Any idea what caused this?
 
--Mark

**Comment by cwulfman** [comment]
I discovered one line missing in the TEI (what is now line 5932) and typed it in.  Could you verify that this is all that was missing?

**Comment by ma20** [comment]
Not sure what happened here, but all looks fine now.
