### ISSUE TITLE
1510-1-12-16 ??

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-catalogo#27]
@joycebcat Could you have a look at 

https://bibdata.princeton.edu/bibliographic/8545532?

The `024` is `1510-1-12-16`, but I'm not sure why--as far as I can tell from the TEI (it's tough to navigate on Github, but here: https://raw.githubusercontent.com/pulibrary/cicognara-catalogo/master/catalogo1.tei.xml) it should just be `1510`. Any ideas?

**Comment by joycebcat** [comment]
@jpstroop Yep, something strange happened here.  I adjusted the bib record.  It should have been just "1510".

**Comment by jpstroop** [comment]
Thanks! I'll close this issue when I fix it in the local copy of the data.
