### ISSUE TITLE
Line 364, n=4, two extents

### ISSUE THREAD

**Issue by lmas2019** [pulibrary/cicognara-catalogo#3]
Item number 4 appears to have two extents - I made a note beside the item.
I ask Marc and he's not sure why there would be two extents - perhaps one is superfulous? Will I mark both extents?

**Comment by cwulfman** [comment]
Looks to me as though there are two editions, both published in Paris:

1766, 3 volumes in octavo;
1780, unknown number of volumes in octavo.

This is messy, but for now I think I’d capture both editions and both extents and we can worry about linking them up later:

 <extent>3 vol. in 8</extent>, <pubPlace>Paris</pubPlace> <date>1766</date> <date>1780</date>, <extent>in 8</extent>


On Feb 21, 2016, at 8:47 PM, lmas2019 <notifications@github.com<mailto:notifications@github.com>> wrote:


Item number 4 appears to have two extents - I made a note beside the item.
I ask Marc and he's not sure why there would be two extents - perhaps one is superfulous? Will I mark both extents?
