### ISSUE TITLE
Joyce needs a dclnum for Cicognara 373

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-catalogo#34]
related to #18

**Comment by cwulfman** [comment]
assigned cico:j8q in TEI file; popped this id from the unused_dclnums list, which is now in the catalogo repository. I don't know where else it is being maintained; @jpstroop , can you tell us how you would like to manage that list?

**Comment by jpstroop** [comment]
@cwulfman, I don't have a better answer than your solution.
