### ISSUE TITLE
Part of Catalogo 3094 should be Catalogo 31

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-catalogo#38]
There is an error in the TEI and the MARC

Bib: 8524803
DCL: xz9

**Comment by ma20** [comment]
Opened bib 8524803, changed the 024 field from 3094 to 31.  So that part is fixed.

For the TEI, should we move the corresp="cico:xz9" from 3094 to Cicognara 31?

**Comment by jpstroop** [comment]
> For the TEI, should we move the corresp="cico:xz9" from 3094 to Cicognara 31?

Yes.

**Comment by cwulfman** [comment]
Ok -- I'll do that for the tei.

**Comment by escowles** [comment]
This was fixed by #39
