### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by lmas2019** [pulibrary/cicognara-catalogo#4]
I may have encountered my first make-things-more-compliated urge that you mentioned might occur(!) Ha! Should I mark apparent subtitles separately from the main title, or tag main and subtitles as one?

**Comment by cwulfman** [comment]
I defer to Mark on this one, but I’d suggest tagging it all as one title for now.

On Feb 21, 2016, at 8:55 PM, lmas2019 <notifications@github.com<mailto:notifications@github.com>> wrote:


I may have encountered my first make-things-more-compliated urge that you mentioned might occur(!) Ha! Should I mark apparent subtitles separately from the main title, or tag main and subtitles as one?
