### ISSUE TITLE
Split objects for Bib 8524808 and Bib 8524703

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-catalogo#74]
Looks like we have two separate editions of that have been bundled on the bib record for the later edition.

https://figgy.princeton.edu/catalog/4b371684-543c-4e0a-982c-605c5d693194
https://figgy.princeton.edu/catalog/3fe3d3b4-8014-4e3c-a715-428c9ec05d3e

I have just gone through all the volumes on these two items and renamed all the volumes correctly (identifying which ones were published in 1809).

Could I ask you to:
create a new Figgy master record for bib 8524808,
transfer all volumes with a parenthetical (1809) in the name to that,
save all the 1815-17 volumes for which our team has created structmaps,
and zap the rest?

**Comment by smallfind** [comment]
I think I've fixed this successfully. 

The 1809 edition is here: https://figgy.princeton.edu/catalog/dbd18a0a-4d44-497f-aed7-fdd27b320092
I've deleted one copy that was missing a volume: https://figgy.princeton.edu/catalog/3fe3d3b4-8014-4e3c-a715-428c9ec05d3e
The remaining Figgy copy of the 1815-17 edition is here: https://figgy.princeton.edu/catalog/4b371684-543c-4e0a-982c-605c5d693194
