### ISSUE TITLE
Automatic "bibl" and "note" tagging stopped

### ISSUE THREAD

**Issue by lmas2019** [pulibrary/cicognara-catalogo#8]
When I reached item 271 (ish), the items are no longer tagged with "bibl" and "note". This is the case for as far as I can see in the rest of Catalog 1. Is there a reason for this? Should I continue to add them manually?

**Comment by cwulfman** [comment]
I'm not sure why I stopped tagging the "bibl" and "note" elements at that point. Yes: please do continue to add them by hand.
