### ISSUE TITLE
Cico No 2924 has wrong fiche 'Dubia' attached, should be dcl:p85 but is dcl:p86

### ISSUE THREAD

**Issue by lightgivener** [pulibrary/cicognara-catalogo#87]
Hey!

The Medailles record has the wrong fiche ('Dubia', header no 2849) attached. The Medailles record is dcl:p86 and the wrongly attached 'Dubia' should instead be dcl:3wm.

https://figgy.princeton.edu/catalog/73ea73df-7388-46d0-b14f-afca969ca63c

(Be aware that there are two Dubia records! The other one is already correctly attached with dcl:p85 here: https://figgy.princeton.edu/catalog/abbe3433-2161-41e0-822c-7bc97ad6e687 )

This is what it's supposed to look like:

Cico-Nr. | Double   Number | Author | Title | Place | Year | Cico-Nr. / Original  (as on fiche   header) | Shot List   Fiche | DCL Nr
-- | -- | -- | -- | -- | -- | -- | -- | --
2849 | (1st copy) | Fröhlich,   Erasmus | Dubia de   Minnisari aliorumque Armeniae | Viennae   Austriae : Trattner | 1754 | 2848(2)=2849 | 2848 (2)    = 2849 | p85
2849 | (2nd copy) | Fröhlich,   Erasmus | Dubia de   Minnisari aliorumque Armeniae  | Viennae   Austriae : Trattner | 1754 | 2849 | 2849     = IV M 42(4) | 3wm

**Comment by lightgivener** [comment]
PS: the MEdailles dcl:p86 already correctly exists so no need to worry about that!

https://figgy.princeton.edu/catalog/5f3a6e13-493f-476c-95d6-9cd9bf1302e6 


thanks!

**Comment by escowles** [comment]
I've updated https://figgy.princeton.edu/catalog/73ea73df-7388-46d0-b14f-afca969ca63c to be dcl:3wm
